// src/data.js

export const movies = [
  {
    id: 1,
    title: 'Побег из Шоушенка',
    year: 1994,
    rating: 9.1,
    votes: 1250000,
    genre: 'Драма',
    poster: '🎬',
  },
  {
    id: 2,
    title: 'Крёстный отец',
    year: 1972,
    rating: 9.0,
    votes: 890000,
    genre: 'Драма',
    poster: '🎥',
  },
  {
    id: 3,
    title: 'Тёмный рыцарь',
    year: 2008,
    rating: 8.9,
    votes: 1180000,
    genre: 'Боевик',
    poster: '🦇',
  },
  {
    id: 4,
    title: 'Криминальное чтиво',
    year: 1994,
    rating: 8.8,
    votes: 1020000,
    genre: 'Криминал',
    poster: '💼',
  },
  {
    id: 5,
    title: 'Интерстеллар',
    year: 2014,
    rating: 8.7,
    votes: 980000,
    genre: 'Фантастика',
    poster: '🚀',
  },
  {
    id: 6,
    title: 'Начало',
    year: 2010,
    rating: 8.8,
    votes: 1130000,
    genre: 'Фантастика',
    poster: '🌀',
  },
  {
    id: 7,
    title: 'Форрест Гамп',
    year: 1994,
    rating: 8.8,
    votes: 1090000,
    genre: 'Драма',
    poster: '🏃',
  },
  {
    id: 8,
    title: 'Матрица',
    year: 1999,
    rating: 8.7,
    votes: 1120000,
    genre: 'Фантастика',
    poster: '💊',
  },
  {
    id: 9,
    title: 'Бойцовский клуб',
    year: 1999,
    rating: 8.8,
    votes: 1250000,
    genre: 'Триллер',
    poster: '🥊',
  },
  {
    id: 10,
    title: 'Леон',
    year: 1994,
    rating: 8.7,
    votes: 720000,
    genre: 'Боевик',
    poster: '🌱',
  },
];

export const shows = [
  {
    id: 1,
    title: 'Во все тяжкие',
    year: 2008,
    rating: 9.5,
    votes: 1560000,
    genre: 'Криминал',
    poster: '🧪',
  },
  {
    id: 2,
    title: 'Игра престолов',
    year: 2011,
    rating: 9.2,
    votes: 2140000,
    genre: 'Фэнтези',
    poster: '🐉',
  },
  {
    id: 3,
    title: 'Чернобыль',
    year: 2019,
    rating: 9.4,
    votes: 832000,
    genre: 'Драма',
    poster: '☢️',
  },
  {
    id: 4,
    title: 'Клан Сопрано',
    year: 1999,
    rating: 9.2,
    votes: 402000,
    genre: 'Криминал',
    poster: '🚬',
  },
  {
    id: 5,
    title: 'Очень странные дела',
    year: 2016,
    rating: 8.7,
    votes: 1180000,
    genre: 'Фантастика',
    poster: '🎸',
  },
  {
    id: 6,
    title: 'Мир Дикого Запада',
    year: 2016,
    rating: 8.5,
    votes: 512000,
    genre: 'Фантастика',
    poster: '🤖',
  },
  {
    id: 7,
    title: 'Шерлок',
    year: 2010,
    rating: 9.1,
    votes: 985000,
    genre: 'Детектив',
    poster: '🔍',
  },
  {
    id: 8,
    title: 'Друзья',
    year: 1994,
    rating: 8.9,
    votes: 1080000,
    genre: 'Комедия',
    poster: '☕',
  },
  {
    id: 9,
    title: 'Рик и Морти',
    year: 2013,
    rating: 9.1,
    votes: 720000,
    genre: 'Мультфильм',
    poster: '🧬',
  },
  {
    id: 10,
    title: 'Настоящий детектив',
    year: 2014,
    rating: 9.0,
    votes: 620000,
    genre: 'Детектив',
    poster: '🕵️',
  },
];

export const music = [
  {
    id: 1,
    artist: 'Radiohead',
    album: 'OK Computer',
    year: 1997,
    rating: 9.1,
    listeners: 8420000,
    genre: 'Alternative Rock',
    cover: '🎸',
  },
  {
    id: 2,
    artist: 'Pink Floyd',
    album: 'The Dark Side of the Moon',
    year: 1973,
    rating: 9.4,
    listeners: 11200000,
    genre: 'Progressive Rock',
    cover: '🌑',
  },
  {
    id: 3,
    artist: 'Nirvana',
    album: 'Nevermind',
    year: 1991,
    rating: 8.9,
    listeners: 9840000,
    genre: 'Grunge',
    cover: '🏊',
  },
  {
    id: 4,
    artist: 'Daft Punk',
    album: 'Discovery',
    year: 2001,
    rating: 8.8,
    listeners: 6210000,
    genre: 'Electronic',
    cover: '🤖',
  },
  {
    id: 5,
    artist: 'Arctic Monkeys',
    album: 'AM',
    year: 2013,
    rating: 8.6,
    listeners: 8950000,
    genre: 'Indie Rock',
    cover: '🌙',
  },
  {
    id: 6,
    artist: 'Kendrick Lamar',
    album: 'To Pimp a Butterfly',
    year: 2015,
    rating: 8.9,
    listeners: 5420000,
    genre: 'Hip-Hop',
    cover: '🦋',
  },
  {
    id: 7,
    artist: 'The Beatles',
    album: 'Abbey Road',
    year: 1969,
    rating: 9.3,
    listeners: 14200000,
    genre: 'Rock',
    cover: '🚶',
  },
  {
    id: 8,
    artist: 'Queen',
    album: 'A Night at the Opera',
    year: 1975,
    rating: 9.0,
    listeners: 12800000,
    genre: 'Rock',
    cover: '👑',
  },
  {
    id: 9,
    artist: 'Muse',
    album: 'Absolution',
    year: 2003,
    rating: 8.7,
    listeners: 7320000,
    genre: 'Alternative Rock',
    cover: '🎹',
  },
  {
    id: 10,
    artist: 'Linkin Park',
    album: 'Hybrid Theory',
    year: 2000,
    rating: 8.8,
    listeners: 10500000,
    genre: 'Nu Metal',
    cover: '🎤',
  },
];

export const facts = [
  'Мёд не портится: археологи находили съедобный мёд в гробницах возрастом 3000 лет.',
  'Осьминоги имеют три сердца. Два качают кровь к жабрам, одно — к остальному телу.',
  'Бананы — ягоды, а малина — нет. С ботанической точки зрения.',
  'Первая компьютерная программа была написана Адой Лавлейс в 1843 году для машины, которой ещё не существовало.',
  'Венера — единственная планета Солнечной системы, вращающаяся по часовой стрелке.',
  'Человеческий нос различает около 1 триллиона различных запахов.',
  'Группа The Beatles изначально называлась The Quarrymen.',
  'Сердце синего кита размером с небольшой автомобиль, а его язык может весить как слон.',
  'Улитки могут спать до трёх лет подряд.',
  'Первая веб-камера была создана в Кембридже, чтобы следить за кофеваркой.',
  'Полярные медведи — левши. Они используют левую лапу для охоты.',
  'Пизанская башня начала наклоняться ещё во время строительства в 1173 году.',
  'В теле человека столько железа, что из него можно сделать гвоздь длиной 7 см.',
  'Слово «робот» придумал чешский писатель Карел Чапек в 1920 году.',
  'Молния в 5 раз горячее поверхности Солнца.',
];
